apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CS-DI-IOC-01
  title: CS-DI-IOC-01
  description: Collects readings and simple controls for all storage ring BPMs
spec:
  type: service
  lifecycle: experimental
  owner: group:default/accelerator-controls
