#!/bin/sh

# Script for publishing concentrator.  Gleaned from similar scripts for
# Diagnostics and Libera components.


function Error()
{
    echo >&2 "$@"
    exit 1
}


Error 'Better fix this first: remember moving it from CS/DI?'


# Checks that the given directory is completely in step with svn.  Unknown
# files (flagged by ?) are ignored.
#
#   CheckSvnCurrent <working-dir>
#
function CheckSvnCurrent()
{
    svn status -u "$1" |
    # We ignore both lines beginning with '?' (these are files that haven't
    # been added: it can be a bit much to insist on adding these) and the
    # 'Status against revision' line that comes from the -u flag.
    sed '/^\?/d
        /^Status against revision:/d
        /^$/d' |
    wc -l |
    { read count && ((count == 0)); }
    # Return success only if the svn status command succeeded and no lines
    # were reported as unresolved.
    ((${PIPESTATUS[0]}==0 && ${PIPESTATUS[3]}==0))
}

function MajorVersion()
{
    svn ls "$1" |
    # Parse out only lines of the form *-*, returning the first component
    # (the major version number).
    sed -n '/^\([0-9][0-9]*\)-.*$/{s//\1/;p;}' |
    sort -n |
    tail -1
    return ${PIPESTATUS[0]}
}

function MinorVersion()
{
    svn ls "$1" |
    # Parse out only lines of the form <major>-*, returning the second
    # component (the minor version number).
    sed -n '/^'"$2"'-\([0-9][0-9]*\)[/]$/{s//\1/;p;}' |
    sort -n |
    tail -1
    return ${PIPESTATUS[0]}
}



SVN_RELEASE="$SVN_ROOT/diamond/release/ioc/CS/DI"
# This is where the released software will be finally published and built.
PROD_ROOT="/dls_sw/prod/R3.14.8.2/ioc/CS/DI"




cd "$(dirname "$0")"

# Check that we're up to date with subversion.  
CheckSvnCurrent . ||
    Error "Some concentrator files not checked in"


# Compute the version number for the new version we're about to release.
CURRENT_MAJOR=$(($(MajorVersion "$SVN_RELEASE")))
CURRENT_MINOR=$(($(MinorVersion "$SVN_RELEASE" $CURRENT_MAJOR)))
VERSION=$CURRENT_MAJOR-$((CURRENT_MINOR+1))


dls-release.py -i CS/DI $VERSION  ||
    Error "Problem making subversion release"



# Finally update the redirector to point to the new installation
configure-ioc b <<EOF
-f CS-DI-IOC-01 $PROD_ROOT/$VERSION/CS-DI-IOC-01/start-ioc
-f CS-DI-IOC-02 $PROD_ROOT/$VERSION/CS-DI-IOC-02/start-ioc
-f CS-DI-IOC-03 $PROD_ROOT/$VERSION/CS-DI-IOC-03/start-ioc
-f CS-DI-IOC-04 $PROD_ROOT/$VERSION/CS-DI-IOC-04/start-ioc
EOF


# Valedictory remarks
cat <<EOF
Concentrator version $VERSION now scheduled to be published.
To complete the installation, restart it using the following procedure:

    1.  Log in to cs03r-cs-ioc-01 (primary network)
    2.  Run
        $ sudo /sbin/service epics-soft-iocs restart CS-DI-IOC-01
        $ sudo /sbin/service epics-soft-iocs restart CS-DI-IOC-02
        $ sudo /sbin/service epics-soft-iocs restart CS-DI-IOC-03
        $ sudo /sbin/service epics-soft-iocs restart CS-DI-IOC-04

The concentrator will then need to be manually reconfigured: simply reload all
menu entries marked as "Inconsistent".
EOF
