#!/bin/sh

PYIOC_VERSION=2-0
PYIOC=/dls_sw/prod/R3.14.11/support/pythonSoftIoc/$PYIOC_VERSION/pythonIoc

export EPICS_BASE=/dls_sw/epics/R3.14.11/base

cd "$(dirname "$0")"
exec $PYIOC concentrator.py
