#!/bin/sh

PYIOC_VERSION=1-2
PYIOC=/dls_sw/prod/R3.14.8.2/support/pythonSoftIoc/$PYIOC_VERSION/pythonIoc

# For development
# PYIOC=/home/mga83/epics/pythonSoftIoc/pythonIoc

cd "$(dirname "$0")"
$PYIOC concentrator.py
