#!/bin/sh

PYIOC_VERSION=2-11
PYIOC=/dls_sw/prod/R3.14.12.3/support/pythonSoftIoc/$PYIOC_VERSION/pythonIoc
PYIOC=/home/mga83/epics/pythonSoftIoc/pythonIoc

[ -n "$1" ]  &&  export EPICS_CAS_SERVER_PORT=6064

cd "$(dirname "$0")"
exec $PYIOC -u concentrator.py "$@"
