#!/bin/sh

. /dls_sw/etc/profile


# Simple script to run the edm shell with PVs only fetched from a locally
# running copy of the server.

# export EPICS_CA_ADDR_LIST=localhost
# export EPICS_CA_AUTO_ADDR_LIST=NO

if (($#)); then
    export EPICS_CA_SERVER_PORT=6064
    export EPICS_CA_REPEATER_PORT=6065
    "$@"
else
    runedm -p 6064 sr
fi
