#!/bin/sh

PYIOC_VERSION=2-4
PYIOC=/dls_sw/prod/R3.14.11/support/pythonSoftIoc/$PYIOC_VERSION/pythonIoc
# PYIOC=/home/mga83/epics/pythonSoftIoc/pythonIoc

export EPICS_BASE=/dls_sw/epics/R3.14.11/base

export EPICS_CAS_SERVER_PORT=6064

cd "$(dirname "$0")"
exec $PYIOC testioc.py
